### ISSUE TITLE
Shadow on rounded corner + red button

### ISSUE THREAD

**Issue by re1** [ishovkun/SierraBreeze#8] opened 2017-12-25 10:46 UTC
Hey there,
Just wanted to ask if it is possible to remove the window shadow for the rounded corners without dropping it completely.
![image](https://user-images.githubusercontent.com/10999017/34338362-4e4e5fa0-e968-11e7-975b-03bdbc61c957.png)
Also, when using the `circle around close-button` there are light pixels around the red button. Can this be disabled by default?

**Comment by dimador** [comment] 2017-12-25 11:47
Is there any chance, that there will be no rounded corners at all? Older version without them looks better on lower-resolution screen. On my 1366x768 screen 9 px rounded corners looks weird.

**Comment by GrayJack** [comment] 2018-02-23 15:13
I also have the shadow problem on corners

**Comment by Magentium-Chris** [comment] 2018-03-10 10:10
Confirmed. I have the shadow issues on corners too. I have had to move to BreezeMite in the meantime :(

**Comment by JoMas971** [comment] 2018-03-17 23:20
Same for me. And BreezeMite is not an option for me sadly :-(. It would be cool to have this fixed :-D.

**Comment by ishovkun** [comment] 2018-05-01 16:37
In the latest commit I use a lower corner radius, and this issue seems to be no longer relevant. I am closing this. Please, open if the issue persists. 
P.S. If somebody likes the corners more rounded, change the FrameRadius value on line 41 in breeze.h.

**Closed** 2018-05-01 16:38 UTC
