### ISSUE TITLE
[Suggestion] SierraBreeze Light (no dark bar)

### ISSUE THREAD

**Issue by nicosea** [ishovkun/SierraBreeze#16] opened 2018-04-09 21:46 UTC
Would it be possible to make also a version light?

**Comment by IgnusG** [comment] 2018-04-10 08:53
Maybe duplicate of https://github.com/ishovkun/SierraBreeze/issues/11

Did you try changing the color scheme?

**Comment by nicosea** [comment] 2018-04-10 09:26
I changed color scheme for Sierra Breeze and I managed to have light version, but there a thin horizontal line in light blue color which separate the top bar of the windows (the one with the bottoms) form the bottom.

Breezymite has the light version without the above issue, but if I put higher DPI (and I have to do it on my screen) I get oversized borders. It is a bug explained in the FAQ. Sierra Breeze does not have it.
________________________________

**Comment by IgnusG** [comment] 2018-04-10 09:38
You mean this bar?
![bluebar](https://user-images.githubusercontent.com/6438760/38549109-a7ecb162-3cb3-11e8-8513-af0b4f29e30f.png)

**Comment by nicosea** [comment] 2018-04-10 10:37
Yes! That bar.

________________________________

**Comment by IgnusG** [comment] 2018-04-10 10:47
I updated my answer on how to remove it - it’s optional ;)

**Comment by nicosea** [comment] 2018-04-10 15:09
Thank you but I do not know how to get in the settings you show in the picture...

________________________________

**Comment by nicosea** [comment] 2018-04-10 15:36
I found how to get there, many thanks!

________________________________

**Comment by IgnusG** [comment] 2018-04-11 19:53
For anyone wondering where to find the option. (PS: I was too lazy to type it out ^^')
![howtoremovebluebar](https://user-images.githubusercontent.com/6438760/38639722-639cbb2c-3dd2-11e8-85f9-ed93b4a2e312.gif)

@nicosea Please feel free to close this issue if this resolved your problem.

**Closed** 2018-04-11 19:56 UTC
